const ingridients = [
  {
    id: "1",
    image: "./images/ingredients/ing-1.jpg",
    weight: "50",
    price: "1.85",
    name: "Parmesan cheese",
  },
  {
    id: "2",
    image: "./images/ingredients/ing-2.jpg",
    weight: "100",
    price: "1.20",
    name: "Mozzarella cheese",
  },
  {
    id: "3",
    image: "./images/ingredients/ing-3.jpg",
    weight: "50",
    price: "1.30",
    name: "Prosciutto",
  },
  {
    id: "4",
    image: "./images/ingredients/ing-4.jpg",
    weight: "50",
    price: "1.10",
    name: "Ham",
  },
  {
    id: "5",
    image: "./images/ingredients/ing-5.jpg",
    weight: "50",
    price: "0.60",
    name: "Mushrooms",
  },
  {
    id: "6",
    image: "./images/ingredients/ing-6.jpg",
    weight: "50",
    price: "0.65",
    name: "Tomatoes",
  },
  {
    id: "7",
    image: "./images/ingredients/ing-7.jpg",
    weight: "50",
    price: "0.70",
    name: "Bell pepper",
  },
  {
    id: "8",
    image: "./images/ingredients/ing-8.jpg",
    weight: "25",
    price: "0.45",
    name: "Chili pepper",
  },
  {
    id: "9",
    image: "./images/ingredients/ing-9.jpg",
    weight: "30",
    price: "0.25",
    name: "Onion",
  },
  {
    id: "10",
    image: "./images/ingredients/ing-11.jpg",
    weight: "50",
    price: "0.50",
    name: "Corn",
  },
  {
    id: "11",
    image: "./images/ingredients/ing-13.jpg",
    weight: "50",
    price: "0.80",
    name: "Pineapple",
  },
  {
    id: "12",
    image: "./images/ingredients/ing-23.jpg",
    weight: "50",
    price: "1",
    name: "Bavarian sausages",
  },
  {
    id: "13",
    image: "./images/ingredients/ing-24.jpg",
    weight: "50",
    price: "1.10",
    name: "Salami sausage",
  },
  {
    id: "14",
    image: "./images/ingredients/ing-25.jpg",
    weight: "50",
    price: "1.05",
    name: "Chicken meat",
  },
  {
    id: "15",
    image: "./images/ingredients/ing-26.jpg",
    weight: "50",
    price: "1",
    name: "Pepperoni",
  },
  {
    id: "16",
    image: "./images/ingredients/ing-28.jpg",
    weight: "50",
    price: "2.10",
    name: "Salmon",
  },
  {
    id: "17",
    image: "./images/ingredients/ing-29.jpg",
    weight: "50",
    price: "1.50",
    name: "Blue cheese",
  },
  {
    id: "18",
    image: "./images/ingredients/olive-black.jpg",
    weight: "50",
    price: "1.20",
    name: "Olives",
  },
];

export const getIngredients = () => {
  return ingridients;
};
